name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]  # runs every day at midnight
  workflow_dispatch:                # allows manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: your-username
          output: metrics.png
          format: png
          config_timezone: Europe/Rome

          # Optional plugins
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_followup: yes
          plugin_stars: yes
